#!/bin/bash
STICK=0

prompt_on_top() {
  tput cup 0 0
  tput el
  tput el1
}

pre_cmd() {
  if [[ $STICK == "0" ]] || [ "$BASH_COMMAND" = "$PROMPT_COMMAND" ] || [ -n "$COMP_LINE" ]; then
    return
  fi
  if [[ "$(uname -a)" =~ "Darwin" ]]; then  # OSX only
    echo ""
    clear 
  else
    printf "\33[2J" 
  fi
}

stick(){
  STICK=1
  PS1_OLD="$PS1"
  export PS1="[\u@\H\[\033[32m\]\w]\[\033[0m\]\[\033[1;33m\]$ \[\033[0m\]"
  export PROMPT_COMMAND="prompt_on_top"
}

unstick(){
  STICK=0
  export PS1="$PS1_OLD"
  export PROMPT_COMMAND='PS1="$PS1"'
}

trap pre_cmd DEBUG
